// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod wasi {
    pub mod random {
        /// WASI Random is a random data API.
        ///
        /// It is intended to be portable at least between Unix-family platforms and
        /// Windows.
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod random {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            /// Return `len` cryptographically-secure random or pseudo-random bytes.
            ///
            /// This function must produce data at least as cryptographically secure and
            /// fast as an adequately seeded cryptographically-secure pseudo-random
            /// number generator (CSPRNG). It must not block, from the perspective of
            /// the calling program, under any circumstances, including on the first
            /// request and on requests for numbers of bytes. The returned data must
            /// always be unpredictable.
            ///
            /// This function must always return fresh data. Deterministic environments
            /// must omit this function, rather than implementing it with deterministic
            /// data.
            pub fn get_random_bytes(len: u64) -> _rt::Vec<u8> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "wasi:random/random@0.2.0")]
                    unsafe extern "C" {
                        #[link_name = "get-random-bytes"]
                        fn wit_import1(_: i64, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: i64, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(_rt::as_i64(&len), ptr0) };
                    let l2 = *ptr0.add(0).cast::<*mut u8>();
                    let l3 = *ptr0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len4 = l3;
                    let result5 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
                    result5
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Return a cryptographically-secure random or pseudo-random `u64` value.
            ///
            /// This function returns the same type of data as `get-random-bytes`,
            /// represented as a `u64`.
            pub fn get_random_u64() -> u64 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "wasi:random/random@0.2.0")]
                    unsafe extern "C" {
                        #[link_name = "get-random-u64"]
                        fn wit_import0() -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    ret as u64
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod junoclaw {
        pub mod sealed_signer {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod signer {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Clone)]
                pub struct KeyInfo {
                    pub address: _rt::String,
                    pub pubkey: _rt::String,
                    pub sealed_blob: _rt::Vec<u8>,
                }
                impl ::core::fmt::Debug for KeyInfo {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("KeyInfo")
                            .field("address", &self.address)
                            .field("pubkey", &self.pubkey)
                            .field("sealed-blob", &self.sealed_blob)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct SignInfo {
                    pub address: _rt::String,
                    pub pubkey: _rt::String,
                    pub signature: _rt::String,
                }
                impl ::core::fmt::Debug for SignInfo {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SignInfo")
                            .field("address", &self.address)
                            .field("pubkey", &self.pubkey)
                            .field("signature", &self.signature)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct CosmosExecuteTxRequest {
                    pub sender: _rt::String,
                    pub contract: _rt::String,
                    pub exec_msg_json: _rt::String,
                    pub funds_denom: _rt::String,
                    pub funds_amount: u64,
                    pub gas_limit: u64,
                    pub fee_denom: _rt::String,
                    pub fee_amount: u64,
                    pub memo: _rt::String,
                    pub chain_id: _rt::String,
                    pub account_number: u64,
                    pub sequence: u64,
                }
                impl ::core::fmt::Debug for CosmosExecuteTxRequest {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("CosmosExecuteTxRequest")
                            .field("sender", &self.sender)
                            .field("contract", &self.contract)
                            .field("exec-msg-json", &self.exec_msg_json)
                            .field("funds-denom", &self.funds_denom)
                            .field("funds-amount", &self.funds_amount)
                            .field("gas-limit", &self.gas_limit)
                            .field("fee-denom", &self.fee_denom)
                            .field("fee-amount", &self.fee_amount)
                            .field("memo", &self.memo)
                            .field("chain-id", &self.chain_id)
                            .field("account-number", &self.account_number)
                            .field("sequence", &self.sequence)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct SignedCosmosTx {
                    pub address: _rt::String,
                    pub pubkey: _rt::String,
                    pub tx_bytes: _rt::Vec<u8>,
                    pub sign_doc_sha256_hex: _rt::String,
                }
                impl ::core::fmt::Debug for SignedCosmosTx {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SignedCosmosTx")
                            .field("address", &self.address)
                            .field("pubkey", &self.pubkey)
                            .field("tx-bytes", &self.tx_bytes)
                            .field("sign-doc-sha256-hex", &self.sign_doc_sha256_hex)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_generate_key_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::generate_key();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(e) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                            let KeyInfo {
                                address: address2,
                                pubkey: pubkey2,
                                sealed_blob: sealed_blob2,
                            } = e;
                            let vec3 = (address2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = (pubkey2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr1
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = (sealed_blob2).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr1
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr1
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec6 = (e.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_generate_key<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base7 = l5;
                            let len7 = l6;
                            _rt::cabi_dealloc(base7, len7 * 1, 1);
                        }
                        _ => {
                            let l8 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l8, l9, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_sign_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let len1 = arg3;
                    let result2 = T::sign(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        _rt::Vec::from_raw_parts(arg2.cast(), len1, len1),
                    );
                    let ptr3 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result2 {
                        Ok(e) => {
                            *ptr3.add(0).cast::<u8>() = (0i32) as u8;
                            let SignInfo {
                                address: address4,
                                pubkey: pubkey4,
                                signature: signature4,
                            } = e;
                            let vec5 = (address4.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                            let vec6 = (pubkey4.into_bytes()).into_boxed_slice();
                            let ptr6 = vec6.as_ptr().cast::<u8>();
                            let len6 = vec6.len();
                            ::core::mem::forget(vec6);
                            *ptr3
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len6;
                            *ptr3
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr6.cast_mut();
                            let vec7 = (signature4.into_bytes()).into_boxed_slice();
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            ::core::mem::forget(vec7);
                            *ptr3
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len7;
                            *ptr3
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr7.cast_mut();
                        }
                        Err(e) => {
                            *ptr3.add(0).cast::<u8>() = (1i32) as u8;
                            let vec8 = (e.into_bytes()).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr3
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr3
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr8.cast_mut();
                        }
                    };
                    ptr3
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_sign<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l5, l6, 1);
                        }
                        _ => {
                            let l7 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l7, l8, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_sign_cosmos_execute_tx_cabi<T: Guest>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len2 = l1;
                    let l3 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l4 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len5 = l4;
                    let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                    let l6 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l7 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len8 = l7;
                    let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                    let l9 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l10 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len11 = l10;
                    let bytes11 = _rt::Vec::from_raw_parts(l9.cast(), len11, len11);
                    let l12 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l13 = *arg0
                        .add(9 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len14 = l13;
                    let bytes14 = _rt::Vec::from_raw_parts(l12.cast(), len14, len14);
                    let l15 = *arg0
                        .add(10 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>();
                    let l16 = *arg0
                        .add(8 + 10 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>();
                    let l17 = *arg0
                        .add(16 + 10 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l18 = *arg0
                        .add(16 + 11 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len19 = l18;
                    let bytes19 = _rt::Vec::from_raw_parts(l17.cast(), len19, len19);
                    let l20 = *arg0
                        .add(16 + 12 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>();
                    let l21 = *arg0
                        .add(24 + 12 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l22 = *arg0
                        .add(24 + 13 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len23 = l22;
                    let bytes23 = _rt::Vec::from_raw_parts(l21.cast(), len23, len23);
                    let l24 = *arg0
                        .add(24 + 14 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l25 = *arg0
                        .add(24 + 15 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let len26 = l25;
                    let bytes26 = _rt::Vec::from_raw_parts(l24.cast(), len26, len26);
                    let l27 = *arg0
                        .add(24 + 16 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>();
                    let l28 = *arg0
                        .add(32 + 16 * ::core::mem::size_of::<*const u8>())
                        .cast::<i64>();
                    let result29 = T::sign_cosmos_execute_tx(
                        _rt::Vec::from_raw_parts(l0.cast(), len2, len2),
                        CosmosExecuteTxRequest {
                            sender: _rt::string_lift(bytes5),
                            contract: _rt::string_lift(bytes8),
                            exec_msg_json: _rt::string_lift(bytes11),
                            funds_denom: _rt::string_lift(bytes14),
                            funds_amount: l15 as u64,
                            gas_limit: l16 as u64,
                            fee_denom: _rt::string_lift(bytes19),
                            fee_amount: l20 as u64,
                            memo: _rt::string_lift(bytes23),
                            chain_id: _rt::string_lift(bytes26),
                            account_number: l27 as u64,
                            sequence: l28 as u64,
                        },
                    );
                    _rt::cabi_dealloc(
                        arg0,
                        40 + 16 * ::core::mem::size_of::<*const u8>(),
                        8,
                    );
                    let ptr30 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result29 {
                        Ok(e) => {
                            *ptr30.add(0).cast::<u8>() = (0i32) as u8;
                            let SignedCosmosTx {
                                address: address31,
                                pubkey: pubkey31,
                                tx_bytes: tx_bytes31,
                                sign_doc_sha256_hex: sign_doc_sha256_hex31,
                            } = e;
                            let vec32 = (address31.into_bytes()).into_boxed_slice();
                            let ptr32 = vec32.as_ptr().cast::<u8>();
                            let len32 = vec32.len();
                            ::core::mem::forget(vec32);
                            *ptr30
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len32;
                            *ptr30
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr32.cast_mut();
                            let vec33 = (pubkey31.into_bytes()).into_boxed_slice();
                            let ptr33 = vec33.as_ptr().cast::<u8>();
                            let len33 = vec33.len();
                            ::core::mem::forget(vec33);
                            *ptr30
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len33;
                            *ptr30
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr33.cast_mut();
                            let vec34 = (tx_bytes31).into_boxed_slice();
                            let ptr34 = vec34.as_ptr().cast::<u8>();
                            let len34 = vec34.len();
                            ::core::mem::forget(vec34);
                            *ptr30
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len34;
                            *ptr30
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr34.cast_mut();
                            let vec35 = (sign_doc_sha256_hex31.into_bytes())
                                .into_boxed_slice();
                            let ptr35 = vec35.as_ptr().cast::<u8>();
                            let len35 = vec35.len();
                            ::core::mem::forget(vec35);
                            *ptr30
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len35;
                            *ptr30
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr35.cast_mut();
                        }
                        Err(e) => {
                            *ptr30.add(0).cast::<u8>() = (1i32) as u8;
                            let vec36 = (e.into_bytes()).into_boxed_slice();
                            let ptr36 = vec36.as_ptr().cast::<u8>();
                            let len36 = vec36.len();
                            ::core::mem::forget(vec36);
                            *ptr30
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len36;
                            *ptr30
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr36.cast_mut();
                        }
                    };
                    ptr30
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_sign_cosmos_execute_tx<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                            let l5 = *arg0
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l6 = *arg0
                                .add(6 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base7 = l5;
                            let len7 = l6;
                            _rt::cabi_dealloc(base7, len7 * 1, 1);
                            let l8 = *arg0
                                .add(7 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *arg0
                                .add(8 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l8, l9, 1);
                        }
                        _ => {
                            let l10 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l11 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l10, l11, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Generate a fresh secp256k1 key from wasi:random/random, seal it with
                    /// WAVS_ENV_SIGNER_PASSPHRASE, and return the Juno bech32 address,
                    /// public key, and the opaque sealed blob.
                    fn generate_key() -> Result<KeyInfo, _rt::String>;
                    /// Decrypt the sealed blob with WAVS_ENV_SIGNER_PASSPHRASE, sign the raw
                    /// message bytes, and return the 64-byte R||S signature as hex.
                    fn sign(
                        message: _rt::Vec<u8>,
                        sealed_blob: _rt::Vec<u8>,
                    ) -> Result<SignInfo, _rt::String>;
                    /// Decrypt the sealed blob with WAVS_ENV_SIGNER_PASSPHRASE, build a
                    /// canonical Cosmos SDK SIGN_MODE_DIRECT transaction wrapping a single
                    /// `cosmwasm.wasm.v1.MsgExecuteContract`, sign it, and return the
                    /// protobuf-encoded TxRaw ready to broadcast. The enclave builds the
                    /// TxBody/AuthInfo/SignDoc itself from these structured fields rather
                    /// than trusting caller-supplied raw bytes, so a caller cannot get the
                    /// enclave to sign anything other than the described contract call.
                    fn sign_cosmos_execute_tx(
                        sealed_blob: _rt::Vec<u8>,
                        req: CosmosExecuteTxRequest,
                    ) -> Result<SignedCosmosTx, _rt::String>;
                }
                #[doc(hidden)]
                macro_rules! __export_junoclaw_sealed_signer_signer_0_3_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "junoclaw:sealed-signer/signer@0.3.0#generate-key")] unsafe
                        extern "C" fn export_generate_key() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_generate_key_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_junoclaw:sealed-signer/signer@0.3.0#generate-key")]
                        unsafe extern "C" fn _post_return_generate_key(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_generate_key::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "junoclaw:sealed-signer/signer@0.3.0#sign")] unsafe extern "C" fn
                        export_sign(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3
                        : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_sign_cabi::<$ty > (arg0, arg1, arg2, arg3) } } #[unsafe
                        (export_name =
                        "cabi_post_junoclaw:sealed-signer/signer@0.3.0#sign")] unsafe
                        extern "C" fn _post_return_sign(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_sign::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "junoclaw:sealed-signer/signer@0.3.0#sign-cosmos-execute-tx")]
                        unsafe extern "C" fn export_sign_cosmos_execute_tx(arg0 : * mut
                        u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_sign_cosmos_execute_tx_cabi::<$ty > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_junoclaw:sealed-signer/signer@0.3.0#sign-cosmos-execute-tx")]
                        unsafe extern "C" fn _post_return_sign_cosmos_execute_tx(arg0 : *
                        mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_sign_cosmos_execute_tx::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_junoclaw_sealed_signer_signer_0_3_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 9 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 9
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_sealed_signer_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::junoclaw::sealed_signer::signer::__export_junoclaw_sealed_signer_signer_0_3_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::junoclaw::sealed_signer::signer);
    };
}
#[doc(inline)]
pub(crate) use __export_sealed_signer_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:junoclaw:sealed-signer@0.3.0:sealed-signer-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 795] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x91\x05\x01A\x02\x01\
A\x04\x01B\x05\x01p}\x01@\x01\x03lenw\0\0\x04\0\x10get-random-bytes\x01\x01\x01@\
\0\0w\x04\0\x0eget-random-u64\x01\x02\x03\0\x18wasi:random/random@0.2.0\x05\0\x01\
B\x12\x01p}\x01r\x03\x07addresss\x06pubkeys\x0bsealed-blob\0\x04\0\x08key-info\x03\
\0\x01\x01r\x03\x07addresss\x06pubkeys\x09signatures\x04\0\x09sign-info\x03\0\x03\
\x01r\x0c\x06senders\x08contracts\x0dexec-msg-jsons\x0bfunds-denoms\x0cfunds-amo\
untw\x09gas-limitw\x09fee-denoms\x0afee-amountw\x04memos\x08chain-ids\x0eaccount\
-numberw\x08sequencew\x04\0\x19cosmos-execute-tx-request\x03\0\x05\x01r\x04\x07a\
ddresss\x06pubkeys\x08tx-bytes\0\x13sign-doc-sha256-hexs\x04\0\x10signed-cosmos-\
tx\x03\0\x07\x01j\x01\x02\x01s\x01@\0\0\x09\x04\0\x0cgenerate-key\x01\x0a\x01j\x01\
\x04\x01s\x01@\x02\x07message\0\x0bsealed-blob\0\0\x0b\x04\0\x04sign\x01\x0c\x01\
j\x01\x08\x01s\x01@\x02\x0bsealed-blob\0\x03req\x06\0\x0d\x04\0\x16sign-cosmos-e\
xecute-tx\x01\x0e\x04\0#junoclaw:sealed-signer/signer@0.3.0\x05\x01\x04\00junocl\
aw:sealed-signer/sealed-signer-world@0.3.0\x04\0\x0b\x19\x01\0\x13sealed-signer-\
world\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.\
1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
