#!/usr/bin/env bash
# Builds both zk-verifier variants (pure-Wasm + precompile) and uploads
# them to the running BN254 devnet. Captures code_ids + contract
# addresses into devnet/deploy.env for the benchmark script.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEVNET_DIR="$(cd "${HERE}/.." && pwd)"
REPO_ROOT="$(cd "${DEVNET_DIR}/.." && pwd)"

CHAIN_ID="${CHAIN_ID:-junoclaw-bn254-1}"
KEYRING="${KEYRING_BACKEND:-test}"
NODE="${NODE:-http://localhost:26657}"
GAS="${GAS:-auto}"
GAS_ADJ="${GAS_ADJUSTMENT:-1.3}"
GAS_PRICES="${GAS_PRICES:-0.025ujuno}"

exec_tx() {
  docker exec junoclaw-bn254-devnet junod tx "$@" \
    --chain-id "${CHAIN_ID}" \
    --keyring-backend "${KEYRING}" \
    --node "${NODE}" \
    --gas "${GAS}" --gas-adjustment "${GAS_ADJ}" --gas-prices "${GAS_PRICES}" \
    --broadcast-mode sync --yes --output json
}

query_ids_from_store() {
  local tx_hash="$1"
  sleep 4 # wait for inclusion
  docker exec junoclaw-bn254-devnet junod query tx "${tx_hash}" \
    --node "${NODE}" --output json | \
    jq -r '.events[] | select(.type == "store_code") | .attributes[] | select(.key == "code_id") | .value' | head -n1
}

# ── 1. Build both flavours. ───────────────────────────────────────────────

echo "[deploy] Building zk-verifier (pure-Wasm)…"
( cd "${REPO_ROOT}/contracts" && \
    cargo build --release --target wasm32-unknown-unknown -p zk-verifier )
WASM_PURE="${REPO_ROOT}/contracts/target/wasm32-unknown-unknown/release/zk_verifier.wasm"
cp "${WASM_PURE}" "${DEVNET_DIR}/zk_verifier_pure.wasm"

echo "[deploy] Building zk-verifier (precompile feature)…"
( cd "${REPO_ROOT}/contracts" && \
    cargo build --release --target wasm32-unknown-unknown -p zk-verifier \
        --features bn254-precompile )
cp "${REPO_ROOT}/contracts/target/wasm32-unknown-unknown/release/zk_verifier.wasm" \
   "${DEVNET_DIR}/zk_verifier_precompile.wasm"

# ── 2. Copy into the container. ───────────────────────────────────────────

docker cp "${DEVNET_DIR}/zk_verifier_pure.wasm"       junoclaw-bn254-devnet:/tmp/
docker cp "${DEVNET_DIR}/zk_verifier_precompile.wasm" junoclaw-bn254-devnet:/tmp/

# ── 3. Store + instantiate both. ─────────────────────────────────────────

ADMIN=$(docker exec junoclaw-bn254-devnet junod keys show admin -a --keyring-backend "${KEYRING}")

echo "[deploy] Uploading pure-Wasm variant…"
PURE_TX=$(exec_tx wasm store /tmp/zk_verifier_pure.wasm --from admin | jq -r '.txhash')
PURE_CODE_ID=$(query_ids_from_store "${PURE_TX}")

echo "[deploy] Uploading precompile variant…"
PREC_TX=$(exec_tx wasm store /tmp/zk_verifier_precompile.wasm --from admin | jq -r '.txhash')
PREC_CODE_ID=$(query_ids_from_store "${PREC_TX}")

echo "[deploy] Instantiating both…"
INIT='{"admin":"'${ADMIN}'"}'
PURE_INIT_TX=$(exec_tx wasm instantiate "${PURE_CODE_ID}" "${INIT}" \
    --from admin --label "zk-verifier-pure" --no-admin | jq -r '.txhash')
PREC_INIT_TX=$(exec_tx wasm instantiate "${PREC_CODE_ID}" "${INIT}" \
    --from admin --label "zk-verifier-precompile" --no-admin | jq -r '.txhash')

sleep 5
PURE_ADDR=$(docker exec junoclaw-bn254-devnet junod query tx "${PURE_INIT_TX}" \
    --node "${NODE}" --output json | \
    jq -r '.events[] | select(.type == "instantiate") | .attributes[] | select(.key == "_contract_address") | .value' | head -n1)
PREC_ADDR=$(docker exec junoclaw-bn254-devnet junod query tx "${PREC_INIT_TX}" \
    --node "${NODE}" --output json | \
    jq -r '.events[] | select(.type == "instantiate") | .attributes[] | select(.key == "_contract_address") | .value' | head -n1)

cat > "${DEVNET_DIR}/deploy.env" <<EOF
# generated by deploy-zk-verifier.sh — consumed by benchmark.sh
CHAIN_ID=${CHAIN_ID}
NODE=${NODE}
PURE_CODE_ID=${PURE_CODE_ID}
PURE_ADDR=${PURE_ADDR}
PRECOMPILE_CODE_ID=${PREC_CODE_ID}
PRECOMPILE_ADDR=${PREC_ADDR}
ADMIN_ADDR=${ADMIN}
EOF

echo "[deploy] Done. Pure addr: ${PURE_ADDR}"
echo "[deploy] Done. Precompile addr: ${PREC_ADDR}"
echo "[deploy] Wrote ${DEVNET_DIR}/deploy.env"
