with open("/mnt/c/cosmos-node/node-data/config/CascadeProjects/windsurf-project/junoclaw/devnet/mayo_vector.hex", "r") as f:
    lines = f.read().splitlines()
pk_hex = lines[1]
sig_hex = lines[3]

out = "// AUTOGENERATED MAYO-2 test vector (seed=[42;32])\n"
out += 'pub const MSG: &[u8] = b"hello mayo pure-rust verifier";\n\n'
out += 'pub const PK_HEX: &str = "' + pk_hex + '" ;\n\n'
out += 'pub const SIG_HEX: &str = "' + sig_hex + '" ;\n\n'
out += 'pub const PK_HASH: &str = "3f245334926d8355301d648fbdf6e3364cc7095594f91668afc81b8aafdb869a";\n'

with open("/mnt/c/cosmos-node/node-data/config/CascadeProjects/windsurf-project/junoclaw/contracts/jclaw-credential/src/mayo_vectors.rs", "w") as f:
    f.write(out)
print("written")
