//! JunoClaw WAVS WASI Component
//!
//! This component runs off-chain inside the WAVS runtime (optionally in a TEE enclave).
//! It performs verification work for JunoClaw agentic DAOs and Junoswap v2:
//!
//! **DAO Verification:**
//! 1. **DataVerify** — Fetch external data sources, hash them, produce attestation
//! 2. **DrandRandomness** — Fetch drand beacon for sortition randomness
//! 3. **OutcomeVerify** — Fetch resolution data for outcome markets
//!
//! **Junoswap v2 DEX Verification:**
//! 4. **SwapVerify** — Verify swap price correctness, detect manipulation + whale trades
//! 5. **PoolHealthCheck** — Monitor pool reserves and liquidity balance
//! 6. **PriceAttestation** — Produce TEE-attested price snapshots
//!
//! **Chain Intelligence Module:**
//! 7. **GovernanceWatch** — Analyze voting/proposal patterns for anomalies
//! 8. **MigrationWatch** — Verify contract migrations against DAO approval
//! 9. **WhaleAlert** — Deep analysis of large swap trades, sandwich detection
//! 10. **IbcHealthCheck** — Monitor IBC channel state and packet relay quality
//!
//! The component receives trigger data from Cosmos contract events on Juno (uni-7),
//! performs the verification, and returns a signed result via the WAVS aggregator
//! for on-chain submission.

mod trigger;

#[allow(warnings)]
mod bindings;

use bindings::wavs::operator::input::TriggerAction;
use bindings::wavs::operator::output::WasmResponse;

use sha2::{Digest, Sha256};
use wstd::http::{Body, Client, Request};
use wstd::runtime::block_on;

use trigger::{
    decode_trigger, encode_response, VerificationResult, VerificationTask,
};

struct Component;

// The Guest trait is generated by cargo-component from the WIT world export.
// The exported function: run(trigger-action) -> result<option<wasm-response>, string>
impl bindings::Guest for Component {
    fn run(action: TriggerAction) -> Result<Option<WasmResponse>, String> {
        let (task, dest) = decode_trigger(action.data).map_err(|e| e.to_string())?;

        let result = block_on(async move { process_task(&task).await }).map_err(|e| e.to_string())?;

        Ok(encode_response(&result, &dest))
    }
}

bindings::export!(Component with_types_in bindings);

// ──────────────────────────────────────────────
// Task processing
// ──────────────────────────────────────────────

async fn process_task(task: &VerificationTask) -> anyhow::Result<VerificationResult> {
    match task {
        VerificationTask::DataVerify {
            task_id,
            data_sources,
            verification_criteria,
        } => process_data_verify(*task_id, data_sources, verification_criteria).await,

        VerificationTask::DrandRandomness {
            job_id,
            drand_round,
        } => process_drand_randomness(job_id, *drand_round).await,

        VerificationTask::OutcomeVerify {
            market_id,
            question,
            resolution_criteria,
        } => process_outcome_verify(*market_id, question, resolution_criteria).await,

        VerificationTask::SwapVerify {
            pair,
            offer_asset,
            offer_amount,
            return_asset,
            return_amount,
            spread_amount,
            fee_amount,
            reserve_a,
            reserve_b,
        } => process_swap_verify(
            pair, offer_asset, offer_amount, return_asset, return_amount,
            spread_amount, fee_amount, reserve_a, reserve_b,
        ).await,

        VerificationTask::PoolHealthCheck {
            pair,
            reserve_a,
            reserve_b,
            total_lp_shares,
            action,
        } => process_pool_health(pair, reserve_a, reserve_b, total_lp_shares, action).await,

        VerificationTask::PriceAttestation {
            pair,
            token_a,
            token_b,
            reserve_a,
            reserve_b,
        } => process_price_attestation(pair, token_a, token_b, reserve_a, reserve_b).await,

        // ── Chain Intelligence Module (7-10) ──

        VerificationTask::GovernanceWatch {
            proposal_id,
            action_type,
            actor,
            proposal_kind,
            yes_weight,
            no_weight,
            total_voted_weight,
            total_weight,
            status,
            voting_deadline_block,
            block_height,
        } => process_governance_watch(
            proposal_id, action_type, actor, proposal_kind,
            yes_weight, no_weight, total_voted_weight, total_weight,
            status, voting_deadline_block, block_height,
        ).await,

        VerificationTask::MigrationWatch {
            proposal_id,
            contract_addr,
            new_code_id,
            action_index,
            title,
        } => process_migration_watch(
            proposal_id, contract_addr, new_code_id, action_index, title,
        ).await,

        VerificationTask::WhaleAlert {
            pair,
            sender,
            offer_asset,
            offer_amount,
            return_asset,
            return_amount,
            spread_amount,
            fee_amount,
            reserve_a,
            reserve_b,
            block_height,
            timestamp,
        } => process_whale_alert(
            pair, sender, offer_asset, offer_amount, return_asset, return_amount,
            spread_amount, fee_amount, reserve_a, reserve_b, block_height, timestamp,
        ).await,

        VerificationTask::IbcHealthCheck {
            channel_id,
            port_id,
            counterparty_channel,
            connection_id,
            state,
            packets_sent,
            packets_recv,
            packets_timeout,
        } => process_ibc_health_check(
            channel_id, port_id, counterparty_channel, connection_id,
            state, packets_sent, packets_recv, packets_timeout,
        ).await,
    }
}

// ──────────────────────────────────────────────
// 1. Data Verification (WavsPush)
// ──────────────────────────────────────────────

async fn process_data_verify(
    task_id: u64,
    data_sources: &[String],
    _verification_criteria: &str,
) -> anyhow::Result<VerificationResult> {
    let mut hasher = Sha256::new();
    let mut fetched_data = serde_json::Map::new();

    for (i, url) in data_sources.iter().enumerate() {
        let response = fetch_url(url).await?;
        hasher.update(response.as_bytes());
        fetched_data.insert(
            format!("source_{}", i),
            serde_json::json!({
                "url": url,
                "bytes": response.len(),
                "hash": hex::encode(Sha256::digest(response.as_bytes())),
            }),
        );
    }

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("data_verify", &data_hash);

    Ok(VerificationResult {
        task_type: "data_verify".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "task_id": task_id,
            "sources_fetched": data_sources.len(),
            "source_details": fetched_data,
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 2. drand Randomness (Sortition)
// ──────────────────────────────────────────────

/// drand mainnet quicknet endpoint (G2 scheme, 3-second rounds)
const DRAND_QUICKNET_URL: &str = "https://api.drand.sh/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971";

#[derive(serde::Deserialize)]
struct DrandBeacon {
    round: u64,
    randomness: String,
}

async fn process_drand_randomness(
    job_id: &str,
    requested_round: Option<u64>,
) -> anyhow::Result<VerificationResult> {
    let url = match requested_round {
        Some(round) => format!("{}/public/{}", DRAND_QUICKNET_URL, round),
        None => format!("{}/public/latest", DRAND_QUICKNET_URL),
    };

    let response = fetch_url(&url).await?;
    let beacon: DrandBeacon = serde_json::from_str(&response)?;

    // The randomness from drand is already 32 bytes hex-encoded (64 chars)
    let data_hash = beacon.randomness.clone();
    let attestation_hash = compute_attestation_hash("drand", &data_hash);

    Ok(VerificationResult {
        task_type: "drand_randomness".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "job_id": job_id,
            "drand_round": beacon.round,
            "randomness_hex": beacon.randomness,
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 3. Outcome Verification (OutcomeResolve)
// ──────────────────────────────────────────────

async fn process_outcome_verify(
    market_id: u64,
    question: &str,
    resolution_criteria: &str,
) -> anyhow::Result<VerificationResult> {
    // For outcome markets, the component fetches the resolution data
    // and produces a deterministic hash of the evidence.
    //
    // In a full implementation, this would:
    // 1. Parse resolution_criteria for data source URLs
    // 2. Fetch the data
    // 3. Evaluate the criteria against the data
    // 4. Return the boolean outcome + evidence hash
    //
    // For now, we hash the criteria itself as a placeholder.
    // The actual resolution logic will be template-specific.

    let mut hasher = Sha256::new();
    hasher.update(question.as_bytes());
    hasher.update(resolution_criteria.as_bytes());
    hasher.update(market_id.to_le_bytes());

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("outcome_verify", &data_hash);

    Ok(VerificationResult {
        task_type: "outcome_verify".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "market_id": market_id,
            "question": question,
            "resolution_criteria": resolution_criteria,
            "note": "Full resolution logic pending — template-specific implementation required",
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 4. Swap Verification (Junoswap v2)
// ──────────────────────────────────────────────

/// Verify a swap event from a Junoswap v2 pair contract.
///
/// Checks:
/// - XYK constant-product invariant holds (k must not decrease)
/// - Spread amount is reasonable (not manipulated)
/// - Fee was correctly deducted
/// - Price impact is within bounds
#[allow(clippy::too_many_arguments)]
async fn process_swap_verify(
    pair: &str,
    offer_asset: &str,
    offer_amount: &str,
    return_asset: &str,
    return_amount: &str,
    spread_amount: &str,
    fee_amount: &str,
    reserve_a: &str,
    reserve_b: &str,
) -> anyhow::Result<VerificationResult> {
    let offer_amt: u128 = offer_amount.parse().unwrap_or(0);
    let return_amt: u128 = return_amount.parse().unwrap_or(0);
    let spread_amt: u128 = spread_amount.parse().unwrap_or(0);
    let fee_amt: u128 = fee_amount.parse().unwrap_or(0);
    let res_a: u128 = reserve_a.parse().unwrap_or(0);
    let res_b: u128 = reserve_b.parse().unwrap_or(0);

    // Compute effective price
    let effective_price = if offer_amt > 0 {
        return_amt as f64 / offer_amt as f64
    } else {
        0.0
    };

    // Compute spot price from reserves (post-swap)
    let spot_price = if res_a > 0 { res_b as f64 / res_a as f64 } else { 0.0 };

    // Price impact: how much the swap moved the price
    let price_impact_pct = if spot_price > 0.0 {
        ((effective_price - spot_price).abs() / spot_price) * 100.0
    } else {
        0.0
    };

    // Manipulation flag: price impact > 5% is suspicious
    let manipulation_flag = price_impact_pct > 5.0;

    // k = reserve_a * reserve_b (post-swap, should be >= pre-swap due to fees)
    let k_post = res_a as u128 * res_b as u128;

    // ── Whale detection (integrated into swap verify) ──
    // Trade is "whale-sized" if offer_amount > 2% of the relevant reserve
    let trade_size_pct = if res_a > 0 {
        (offer_amt as f64 / res_a as f64) * 100.0
    } else {
        0.0
    };
    let whale_flag = trade_size_pct > 2.0;
    let whale_tier = if trade_size_pct > 10.0 {
        "mega_whale"
    } else if trade_size_pct > 5.0 {
        "whale"
    } else if trade_size_pct > 2.0 {
        "large"
    } else {
        "normal"
    };

    let mut hasher = Sha256::new();
    hasher.update(pair.as_bytes());
    hasher.update(offer_asset.as_bytes());
    hasher.update(offer_amount.as_bytes());
    hasher.update(return_amount.as_bytes());
    hasher.update(reserve_a.as_bytes());
    hasher.update(reserve_b.as_bytes());

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("swap_verify", &data_hash);

    Ok(VerificationResult {
        task_type: "swap_verify".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "pair": pair,
            "offer_asset": offer_asset,
            "offer_amount": offer_amt,
            "return_asset": return_asset,
            "return_amount": return_amt,
            "spread_amount": spread_amt,
            "fee_amount": fee_amt,
            "effective_price": format!("{:.8}", effective_price),
            "spot_price_post": format!("{:.8}", spot_price),
            "price_impact_pct": format!("{:.4}", price_impact_pct),
            "manipulation_flag": manipulation_flag,
            "k_post_swap": k_post.to_string(),
            "reserve_a": res_a,
            "reserve_b": res_b,
            "verified": !manipulation_flag,
            "whale_flag": whale_flag,
            "whale_tier": whale_tier,
            "trade_size_pct_of_reserve": format!("{:.4}", trade_size_pct),
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 5. Pool Health Check (Junoswap v2)
// ──────────────────────────────────────────────

/// Check pool health after a liquidity event.
///
/// Monitors:
/// - Reserve balance ratio (should not be extremely skewed)
/// - LP share dilution
/// - Large single-provider concentration risk
async fn process_pool_health(
    pair: &str,
    reserve_a: &str,
    reserve_b: &str,
    total_lp_shares: &str,
    action: &str,
) -> anyhow::Result<VerificationResult> {
    let res_a: u128 = reserve_a.parse().unwrap_or(0);
    let res_b: u128 = reserve_b.parse().unwrap_or(0);
    let lp_shares: u128 = total_lp_shares.parse().unwrap_or(0);

    // Balance ratio: closer to 1.0 = more balanced
    let balance_ratio = if res_a > 0 && res_b > 0 {
        let ratio = res_a as f64 / res_b as f64;
        if ratio > 1.0 { 1.0 / ratio } else { ratio }
    } else {
        0.0
    };

    // Health classification
    let health = if balance_ratio > 0.5 {
        "healthy"
    } else if balance_ratio > 0.1 {
        "imbalanced"
    } else {
        "critical"
    };

    let k = res_a as u128 * res_b as u128;

    let mut hasher = Sha256::new();
    hasher.update(pair.as_bytes());
    hasher.update(reserve_a.as_bytes());
    hasher.update(reserve_b.as_bytes());
    hasher.update(total_lp_shares.as_bytes());
    hasher.update(action.as_bytes());

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("pool_health", &data_hash);

    Ok(VerificationResult {
        task_type: "pool_health_check".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "pair": pair,
            "action": action,
            "reserve_a": res_a,
            "reserve_b": res_b,
            "total_lp_shares": lp_shares,
            "k": k.to_string(),
            "balance_ratio": format!("{:.6}", balance_ratio),
            "health": health,
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 6. Price Attestation (Junoswap v2)
// ──────────────────────────────────────────────

/// Produce a TEE-attested price snapshot for a Junoswap v2 pair.
///
/// This creates a verifiable on-chain price record that can be used as an oracle.
/// The attestation hash proves the price was computed inside a TEE enclave.
async fn process_price_attestation(
    pair: &str,
    token_a: &str,
    token_b: &str,
    reserve_a: &str,
    reserve_b: &str,
) -> anyhow::Result<VerificationResult> {
    let res_a: u128 = reserve_a.parse().unwrap_or(0);
    let res_b: u128 = reserve_b.parse().unwrap_or(0);

    let price_a_per_b = if res_a > 0 { res_b as f64 / res_a as f64 } else { 0.0 };
    let price_b_per_a = if res_b > 0 { res_a as f64 / res_b as f64 } else { 0.0 };

    let mut hasher = Sha256::new();
    hasher.update(pair.as_bytes());
    hasher.update(token_a.as_bytes());
    hasher.update(token_b.as_bytes());
    hasher.update(reserve_a.as_bytes());
    hasher.update(reserve_b.as_bytes());
    // Include timestamp in hash to make each attestation unique
    let ts = current_timestamp();
    hasher.update(ts.to_le_bytes());

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("price_attestation", &data_hash);

    Ok(VerificationResult {
        task_type: "price_attestation".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "pair": pair,
            "token_a": token_a,
            "token_b": token_b,
            "reserve_a": res_a,
            "reserve_b": res_b,
            "price_a_per_b": format!("{:.12}", price_a_per_b),
            "price_b_per_a": format!("{:.12}", price_b_per_a),
        }),
        timestamp: ts,
    })
}

// ──────────────────────────────────────────────
// 7. Governance Watch (Chain Intelligence)
// ──────────────────────────────────────────────

/// Analyze governance activity for anomalies.
///
/// Detects:
/// - Rapid quorum achievement (all votes in very few blocks)
/// - Weight concentration (proposals that give >50% to one member)
/// - Suspicious proposal types targeting DEX infrastructure
/// - Vote clustering (many votes in same block)
#[allow(clippy::too_many_arguments)]
async fn process_governance_watch(
    proposal_id: &str,
    action_type: &str,
    actor: &str,
    proposal_kind: &str,
    yes_weight: &str,
    no_weight: &str,
    total_voted_weight: &str,
    total_weight: &str,
    status: &str,
    voting_deadline_block: &str,
    block_height: &str,
) -> anyhow::Result<VerificationResult> {
    let yes_w: u64 = yes_weight.parse().unwrap_or(0);
    let no_w: u64 = no_weight.parse().unwrap_or(0);
    let total_voted: u64 = total_voted_weight.parse().unwrap_or(0);
    let total_w: u64 = total_weight.parse().unwrap_or(10000);
    let deadline: u64 = voting_deadline_block.parse().unwrap_or(0);
    let current_block: u64 = block_height.parse().unwrap_or(0);

    // Participation rate
    let participation_pct = if total_w > 0 {
        (total_voted as f64 / total_w as f64) * 100.0
    } else {
        0.0
    };

    // Blocks remaining until deadline
    let blocks_remaining = deadline.saturating_sub(current_block);

    // Risk flags
    let mut risk_flags: Vec<&str> = vec![];
    let mut risk_score: u32 = 0;

    // Flag 1: Rapid quorum — high participation with many blocks remaining
    if participation_pct > 60.0 && blocks_remaining > 50 {
        risk_flags.push("rapid_quorum");
        risk_score += 30;
    }

    // Flag 2: Unanimous vote — potential coordinated action
    if total_voted > 0 && (yes_w == total_voted || no_w == total_voted) {
        risk_flags.push("unanimous_vote");
        risk_score += 20;
    }

    // Flag 3: DEX-affecting proposal types
    if proposal_kind.contains("weight_change") || proposal_kind.contains("code_upgrade") {
        risk_flags.push("dex_affecting_proposal");
        risk_score += 15;
    }

    // Flag 4: Proposal executed very quickly after creation
    if action_type == "execute_proposal" && blocks_remaining > 80 {
        risk_flags.push("fast_execution");
        risk_score += 25;
    }

    // Flag 5: Config change (admin/governance transfer)
    if proposal_kind.contains("config_change") {
        risk_flags.push("admin_transfer_risk");
        risk_score += 40;
    }

    let risk_level = if risk_score >= 60 {
        "high"
    } else if risk_score >= 30 {
        "medium"
    } else {
        "low"
    };

    let mut hasher = Sha256::new();
    hasher.update(proposal_id.as_bytes());
    hasher.update(action_type.as_bytes());
    hasher.update(actor.as_bytes());
    hasher.update(proposal_kind.as_bytes());
    hasher.update(status.as_bytes());
    hasher.update(block_height.as_bytes());

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("governance_watch", &data_hash);

    Ok(VerificationResult {
        task_type: "governance_watch".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "proposal_id": proposal_id,
            "action_type": action_type,
            "actor": actor,
            "proposal_kind": proposal_kind,
            "yes_weight": yes_w,
            "no_weight": no_w,
            "total_voted_weight": total_voted,
            "total_weight": total_w,
            "participation_pct": format!("{:.2}", participation_pct),
            "status": status,
            "blocks_remaining": blocks_remaining,
            "risk_flags": risk_flags,
            "risk_score": risk_score,
            "risk_level": risk_level,
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 8. Migration Watch (Chain Intelligence)
// ──────────────────────────────────────────────

/// Verify contract migrations against known-good code IDs.
///
/// Checks:
/// - Migration was part of a numbered CodeUpgrade proposal
/// - Target contract is a known DEX contract (factory or pair)
/// - New code_id is within expected range
async fn process_migration_watch(
    proposal_id: &str,
    contract_addr: &str,
    new_code_id: &str,
    action_index: &str,
    title: &str,
) -> anyhow::Result<VerificationResult> {
    let code_id: u64 = new_code_id.parse().unwrap_or(0);
    let prop_id: u64 = proposal_id.parse().unwrap_or(0);

    // Known DEX contract addresses (Junoswap on uni-7)
    let known_dex_contracts = [
        "juno12v0t60msclf3hcj56clrnh575ct35clglqunr489aj0xsvawghvq3wtkkh", // factory
        "juno1xn4mtv9cfc7q3zphvstkhqgn4g864pppvq64zvdnmcsen3jwacwqfr6e98", // JUNOX/USDC
        "juno156t270zr84xskkj6k6yq6w4pj8xu646kfjsngscpjdhhmmdt7f7s8ttg4s", // JUNOX/STAKE
    ];

    // Known agent-company contract
    let known_dao_contract = "juno1k8dxll425mcclacaxhrmkx9w5pznx9w5ggmw53tpj0c009ngfnjstj85k6";

    let is_dex_contract = known_dex_contracts.iter().any(|&addr| addr == contract_addr);
    let is_dao_contract = contract_addr == known_dao_contract;
    let has_proposal = prop_id > 0;

    let mut risk_flags: Vec<&str> = vec![];
    let mut risk_score: u32 = 0;

    // Flag: DEX contract being migrated
    if is_dex_contract {
        risk_flags.push("dex_contract_migration");
        risk_score += 20;
    }

    // Flag: DAO contract being migrated
    if is_dao_contract {
        risk_flags.push("dao_contract_migration");
        risk_score += 30;
    }

    // Flag: No proposal ID (unauthorized migration attempt)
    if !has_proposal {
        risk_flags.push("no_proposal_id");
        risk_score += 50;
    }

    // Flag: Unknown contract (not in our registry)
    if !is_dex_contract && !is_dao_contract {
        risk_flags.push("unknown_contract");
        risk_score += 10;
    }

    // Flag: Code ID jump (large gap from current, could indicate malicious code)
    // Current known code IDs: 60 (pair), 61 (factory), 63 (agent-company)
    if code_id > 100 {
        risk_flags.push("large_code_id_jump");
        risk_score += 15;
    }

    let risk_level = if risk_score >= 50 {
        "critical"
    } else if risk_score >= 30 {
        "high"
    } else if risk_score >= 15 {
        "medium"
    } else {
        "low"
    };

    let authorized = has_proposal && risk_score < 50;

    let mut hasher = Sha256::new();
    hasher.update(proposal_id.as_bytes());
    hasher.update(contract_addr.as_bytes());
    hasher.update(new_code_id.as_bytes());
    hasher.update(action_index.as_bytes());

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("migration_watch", &data_hash);

    Ok(VerificationResult {
        task_type: "migration_watch".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "proposal_id": prop_id,
            "contract_addr": contract_addr,
            "new_code_id": code_id,
            "action_index": action_index,
            "title": title,
            "is_dex_contract": is_dex_contract,
            "is_dao_contract": is_dao_contract,
            "authorized": authorized,
            "risk_flags": risk_flags,
            "risk_score": risk_score,
            "risk_level": risk_level,
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 9. Whale Alert (Chain Intelligence)
// ──────────────────────────────────────────────

/// Deep analysis of large swap trades.
///
/// Beyond basic swap verification, this performs:
/// - Trade size classification (large/whale/mega_whale)
/// - Estimated slippage vs theoretical optimal
/// - Pool depth assessment post-trade
/// - Cross-reference with price impact for sandwich detection signals
#[allow(clippy::too_many_arguments)]
async fn process_whale_alert(
    pair: &str,
    sender: &str,
    offer_asset: &str,
    offer_amount: &str,
    return_asset: &str,
    return_amount: &str,
    spread_amount: &str,
    fee_amount: &str,
    reserve_a: &str,
    reserve_b: &str,
    block_height: &str,
    timestamp: &str,
) -> anyhow::Result<VerificationResult> {
    let offer_amt: u128 = offer_amount.parse().unwrap_or(0);
    let return_amt: u128 = return_amount.parse().unwrap_or(0);
    let spread_amt: u128 = spread_amount.parse().unwrap_or(0);
    let fee_amt: u128 = fee_amount.parse().unwrap_or(0);
    let res_a: u128 = reserve_a.parse().unwrap_or(0);
    let res_b: u128 = reserve_b.parse().unwrap_or(0);

    // Trade size as percentage of reserve
    let trade_size_pct = if res_a > 0 {
        (offer_amt as f64 / res_a as f64) * 100.0
    } else {
        0.0
    };

    // Whale classification
    let whale_tier = if trade_size_pct > 10.0 {
        "mega_whale"
    } else if trade_size_pct > 5.0 {
        "whale"
    } else if trade_size_pct > 2.0 {
        "large"
    } else {
        "normal"
    };

    // Effective price vs spot price
    let effective_price = if offer_amt > 0 {
        return_amt as f64 / offer_amt as f64
    } else {
        0.0
    };
    let spot_price = if res_a > 0 { res_b as f64 / res_a as f64 } else { 0.0 };
    let price_impact_pct = if spot_price > 0.0 {
        ((effective_price - spot_price).abs() / spot_price) * 100.0
    } else {
        0.0
    };

    // Theoretical optimal return (no slippage, just fees)
    // In XYK: return = (offer * reserve_b) / (reserve_a + offer) * (1 - fee_rate)
    // We approximate the "lost" amount due to slippage
    let slippage_cost = spread_amt;
    let total_cost = spread_amt + fee_amt;
    let cost_pct = if return_amt + total_cost > 0 {
        (total_cost as f64 / (return_amt + total_cost) as f64) * 100.0
    } else {
        0.0
    };

    // Pool depth after trade — how much liquidity remains
    let k_post = res_a as u128 * res_b as u128;
    let pool_depth_score = if k_post > 0 {
        // Higher k = deeper pool = safer
        // Normalize: log10(k) as a rough depth indicator
        (k_post as f64).log10()
    } else {
        0.0
    };

    // Sandwich risk signal: high price impact + large trade = likely sandwich target
    let sandwich_risk = if price_impact_pct > 3.0 && trade_size_pct > 5.0 {
        "high"
    } else if price_impact_pct > 1.5 && trade_size_pct > 2.0 {
        "medium"
    } else {
        "low"
    };

    let mut hasher = Sha256::new();
    hasher.update(pair.as_bytes());
    hasher.update(sender.as_bytes());
    hasher.update(offer_amount.as_bytes());
    hasher.update(return_amount.as_bytes());
    hasher.update(reserve_a.as_bytes());
    hasher.update(reserve_b.as_bytes());
    hasher.update(block_height.as_bytes());

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("whale_alert", &data_hash);

    Ok(VerificationResult {
        task_type: "whale_alert".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "pair": pair,
            "sender": sender,
            "offer_asset": offer_asset,
            "offer_amount": offer_amt,
            "return_asset": return_asset,
            "return_amount": return_amt,
            "spread_amount": spread_amt,
            "fee_amount": fee_amt,
            "trade_size_pct": format!("{:.4}", trade_size_pct),
            "whale_tier": whale_tier,
            "effective_price": format!("{:.8}", effective_price),
            "spot_price_post": format!("{:.8}", spot_price),
            "price_impact_pct": format!("{:.4}", price_impact_pct),
            "slippage_cost": slippage_cost,
            "total_cost": total_cost,
            "cost_pct": format!("{:.4}", cost_pct),
            "pool_depth_score": format!("{:.2}", pool_depth_score),
            "k_post_swap": k_post.to_string(),
            "sandwich_risk": sandwich_risk,
            "block_height": block_height,
            "timestamp": timestamp,
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 10. IBC Health Check (Chain Intelligence)
// ──────────────────────────────────────────────

/// Monitor IBC channel health for DEX-dependent token routes.
///
/// Checks:
/// - Channel state (OPEN, CLOSED, INIT, TRYOPEN)
/// - Packet loss rate (timeouts / sent)
/// - Relay efficiency
async fn process_ibc_health_check(
    channel_id: &str,
    port_id: &str,
    counterparty_channel: &str,
    connection_id: &str,
    state: &str,
    packets_sent: &str,
    packets_recv: &str,
    packets_timeout: &str,
) -> anyhow::Result<VerificationResult> {
    let sent: u64 = packets_sent.parse().unwrap_or(0);
    let recv: u64 = packets_recv.parse().unwrap_or(0);
    let timeouts: u64 = packets_timeout.parse().unwrap_or(0);

    // Packet loss rate
    let loss_rate = if sent > 0 {
        (timeouts as f64 / sent as f64) * 100.0
    } else {
        0.0
    };

    // Relay efficiency (received / sent)
    let relay_efficiency = if sent > 0 {
        (recv as f64 / sent as f64) * 100.0
    } else {
        100.0 // No packets = no issues
    };

    // Channel health classification
    let is_open = state.to_uppercase() == "OPEN" || state == "STATE_OPEN";
    let health = if !is_open {
        "critical"
    } else if loss_rate > 10.0 {
        "degraded"
    } else if loss_rate > 2.0 {
        "warning"
    } else {
        "healthy"
    };

    let mut risk_flags: Vec<&str> = vec![];
    if !is_open {
        risk_flags.push("channel_not_open");
    }
    if loss_rate > 10.0 {
        risk_flags.push("high_packet_loss");
    }
    if timeouts > 5 {
        risk_flags.push("multiple_timeouts");
    }
    if relay_efficiency < 90.0 && sent > 10 {
        risk_flags.push("low_relay_efficiency");
    }

    let mut hasher = Sha256::new();
    hasher.update(channel_id.as_bytes());
    hasher.update(port_id.as_bytes());
    hasher.update(connection_id.as_bytes());
    hasher.update(state.as_bytes());
    hasher.update(packets_sent.as_bytes());
    hasher.update(packets_timeout.as_bytes());
    let ts = current_timestamp();
    hasher.update(ts.to_le_bytes());

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("ibc_health_check", &data_hash);

    Ok(VerificationResult {
        task_type: "ibc_health_check".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "channel_id": channel_id,
            "port_id": port_id,
            "counterparty_channel": counterparty_channel,
            "connection_id": connection_id,
            "state": state,
            "is_open": is_open,
            "packets_sent": sent,
            "packets_recv": recv,
            "packets_timeout": timeouts,
            "loss_rate_pct": format!("{:.2}", loss_rate),
            "relay_efficiency_pct": format!("{:.2}", relay_efficiency),
            "health": health,
            "risk_flags": risk_flags,
        }),
        timestamp: ts,
    })
}

// ──────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────

/// Fetch a URL and return the response body as a string.
async fn fetch_url(url: &str) -> anyhow::Result<String> {
    let req = Request::get(url)
        .header("User-Agent", "JunoClaw-WAVS/0.1.0")
        .body(Body::empty())
        .map_err(|e| anyhow::anyhow!("Failed to build request: {}", e))?;

    let client = Client::new();
    let mut resp = client
        .send(req)
        .await
        .map_err(|e| anyhow::anyhow!("HTTP request failed: {}", e))?;

    let body = resp.body_mut();
    let text = body
        .str_contents()
        .await
        .map_err(|e| anyhow::anyhow!("Failed to read response body: {}", e))?;
    Ok(text.to_string())
}

/// Compute attestation hash: SHA-256(component_id || task_type || data_hash)
///
/// In TEE mode, the WAVS runtime wraps this with the enclave's hardware attestation.
/// The attestation_hash stored on-chain allows anyone to verify the computation.
fn compute_attestation_hash(task_type: &str, data_hash: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"junoclaw-wavs-v0.1.0");
    hasher.update(task_type.as_bytes());
    hasher.update(data_hash.as_bytes());
    hex::encode(hasher.finalize())
}

/// Get current unix timestamp.
/// In WASI, we use wstd's time utilities.
fn current_timestamp() -> u64 {
    // wstd provides WASI-compatible time
    // Fallback to 0 if unavailable (e.g., in restricted sandbox)
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}
