//! JunoClaw WAVS WASI Component
//!
//! This component runs off-chain inside the WAVS runtime (optionally in a TEE enclave).
//! It performs three types of verification work for JunoClaw agentic DAOs:
//!
//! 1. **DataVerify** — Fetch external data sources, hash them, produce attestation
//!    (used by WavsPush proposals)
//! 2. **DrandRandomness** — Fetch drand beacon for sortition randomness
//!    (used by SortitionRequest proposals when NOIS proxy is unavailable)
//! 3. **OutcomeVerify** — Fetch resolution data for outcome markets
//!    (used by OutcomeResolve proposals)
//!
//! The component receives trigger data from Cosmos contract events on Juno (uni-7),
//! performs the verification, and returns a signed result via the WAVS aggregator
//! for on-chain submission.

mod trigger;

#[allow(warnings)]
mod bindings;

use bindings::wavs::operator::input::TriggerAction;
use bindings::wavs::operator::output::WasmResponse;

use sha2::{Digest, Sha256};
use wstd::http::{Body, Client, Request};
use wstd::runtime::block_on;

use trigger::{
    decode_trigger, encode_response, VerificationResult, VerificationTask,
};

struct Component;

// The Guest trait is generated by cargo-component from the WIT world export.
// The exported function: run(trigger-action) -> result<option<wasm-response>, string>
impl bindings::Guest for Component {
    fn run(action: TriggerAction) -> Result<Option<WasmResponse>, String> {
        let (task, dest) = decode_trigger(action.data).map_err(|e| e.to_string())?;

        let result = block_on(async move { process_task(&task).await }).map_err(|e| e.to_string())?;

        Ok(encode_response(&result, &dest))
    }
}

bindings::export!(Component with_types_in bindings);

// ──────────────────────────────────────────────
// Task processing
// ──────────────────────────────────────────────

async fn process_task(task: &VerificationTask) -> anyhow::Result<VerificationResult> {
    match task {
        VerificationTask::DataVerify {
            task_id,
            data_sources,
            verification_criteria,
        } => process_data_verify(*task_id, data_sources, verification_criteria).await,

        VerificationTask::DrandRandomness {
            job_id,
            drand_round,
        } => process_drand_randomness(job_id, *drand_round).await,

        VerificationTask::OutcomeVerify {
            market_id,
            question,
            resolution_criteria,
        } => process_outcome_verify(*market_id, question, resolution_criteria).await,
    }
}

// ──────────────────────────────────────────────
// 1. Data Verification (WavsPush)
// ──────────────────────────────────────────────

async fn process_data_verify(
    task_id: u64,
    data_sources: &[String],
    _verification_criteria: &str,
) -> anyhow::Result<VerificationResult> {
    let mut hasher = Sha256::new();
    let mut fetched_data = serde_json::Map::new();

    for (i, url) in data_sources.iter().enumerate() {
        let response = fetch_url(url).await?;
        hasher.update(response.as_bytes());
        fetched_data.insert(
            format!("source_{}", i),
            serde_json::json!({
                "url": url,
                "bytes": response.len(),
                "hash": hex::encode(Sha256::digest(response.as_bytes())),
            }),
        );
    }

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("data_verify", &data_hash);

    Ok(VerificationResult {
        task_type: "data_verify".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "task_id": task_id,
            "sources_fetched": data_sources.len(),
            "source_details": fetched_data,
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 2. drand Randomness (Sortition)
// ──────────────────────────────────────────────

/// drand mainnet quicknet endpoint (G2 scheme, 3-second rounds)
const DRAND_QUICKNET_URL: &str = "https://api.drand.sh/52db9ba70e0cc0f6eaf7803dd07447a1f5477735fd3f661792ba94600c84e971";

#[derive(serde::Deserialize)]
struct DrandBeacon {
    round: u64,
    randomness: String,
}

async fn process_drand_randomness(
    job_id: &str,
    requested_round: Option<u64>,
) -> anyhow::Result<VerificationResult> {
    let url = match requested_round {
        Some(round) => format!("{}/public/{}", DRAND_QUICKNET_URL, round),
        None => format!("{}/public/latest", DRAND_QUICKNET_URL),
    };

    let response = fetch_url(&url).await?;
    let beacon: DrandBeacon = serde_json::from_str(&response)?;

    // The randomness from drand is already 32 bytes hex-encoded (64 chars)
    let data_hash = beacon.randomness.clone();
    let attestation_hash = compute_attestation_hash("drand", &data_hash);

    Ok(VerificationResult {
        task_type: "drand_randomness".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "job_id": job_id,
            "drand_round": beacon.round,
            "randomness_hex": beacon.randomness,
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// 3. Outcome Verification (OutcomeResolve)
// ──────────────────────────────────────────────

async fn process_outcome_verify(
    market_id: u64,
    question: &str,
    resolution_criteria: &str,
) -> anyhow::Result<VerificationResult> {
    // For outcome markets, the component fetches the resolution data
    // and produces a deterministic hash of the evidence.
    //
    // In a full implementation, this would:
    // 1. Parse resolution_criteria for data source URLs
    // 2. Fetch the data
    // 3. Evaluate the criteria against the data
    // 4. Return the boolean outcome + evidence hash
    //
    // For now, we hash the criteria itself as a placeholder.
    // The actual resolution logic will be template-specific.

    let mut hasher = Sha256::new();
    hasher.update(question.as_bytes());
    hasher.update(resolution_criteria.as_bytes());
    hasher.update(market_id.to_le_bytes());

    let data_hash = hex::encode(hasher.finalize());
    let attestation_hash = compute_attestation_hash("outcome_verify", &data_hash);

    Ok(VerificationResult {
        task_type: "outcome_verify".to_string(),
        data_hash,
        attestation_hash,
        output: serde_json::json!({
            "market_id": market_id,
            "question": question,
            "resolution_criteria": resolution_criteria,
            "note": "Full resolution logic pending — template-specific implementation required",
        }),
        timestamp: current_timestamp(),
    })
}

// ──────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────

/// Fetch a URL and return the response body as a string.
async fn fetch_url(url: &str) -> anyhow::Result<String> {
    let req = Request::get(url)
        .header("User-Agent", "JunoClaw-WAVS/0.1.0")
        .body(Body::empty())
        .map_err(|e| anyhow::anyhow!("Failed to build request: {}", e))?;

    let client = Client::new();
    let mut resp = client
        .send(req)
        .await
        .map_err(|e| anyhow::anyhow!("HTTP request failed: {}", e))?;

    let body = resp.body_mut();
    let text = body
        .str_contents()
        .await
        .map_err(|e| anyhow::anyhow!("Failed to read response body: {}", e))?;
    Ok(text.to_string())
}

/// Compute attestation hash: SHA-256(component_id || task_type || data_hash)
///
/// In TEE mode, the WAVS runtime wraps this with the enclave's hardware attestation.
/// The attestation_hash stored on-chain allows anyone to verify the computation.
fn compute_attestation_hash(task_type: &str, data_hash: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"junoclaw-wavs-v0.1.0");
    hasher.update(task_type.as_bytes());
    hasher.update(data_hash.as_bytes());
    hex::encode(hasher.finalize())
}

/// Get current unix timestamp.
/// In WASI, we use wstd's time utilities.
fn current_timestamp() -> u64 {
    // wstd provides WASI-compatible time
    // Fallback to 0 if unavailable (e.g., in restricted sandbox)
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}
