//! Deterministic ML-DSA (FIPS 204) test-vector generator.
//!
//! Emits `src/mldsa_vectors.rs` containing seeded, reproducible
//! (public-key, signature) pairs for ML-DSA-44 / 65 / 87 over a fixed
//! message. These static vectors are consumed by:
//!   * the `mldsa_vectors` test module (validity guard), and
//!   * `deploy/benchmark-mldsa-devnet.cjs` (the on-chain gas benchmark, which
//!     cannot generate ML-DSA signatures in JavaScript).
//!
//! Reproduce with:
//!   cargo run -p jclaw-credential --example gen_mldsa_vectors
//!
//! Verification is seed-independent, so regenerating yields byte-identical
//! output as long as `fips204` keeps its keygen/sign-from-seed semantics.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use fips204::traits::{KeyGen, SerDes, Signer};

const MSG: &[u8] = b"aegis :: ml-dsa on-chain attestation vector";

fn hex_encode(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        write!(&mut s, "{b:02x}").unwrap();
    }
    s
}

macro_rules! gen {
    ($module:path, $kg_seed:expr, $sig_seed:expr) => {{
        use $module as m;
        let (pk, sk) = m::KG::keygen_from_seed(&$kg_seed);
        let sig = sk.try_sign_with_seed(&$sig_seed, MSG, &[]).unwrap();
        (hex_encode(&pk.into_bytes()), hex_encode(&sig))
    }};
}

fn main() {
    let (pk44, sig44) = gen!(fips204::ml_dsa_44, [1u8; 32], [2u8; 32]);
    let (pk65, sig65) = gen!(fips204::ml_dsa_65, [3u8; 32], [4u8; 32]);
    let (pk87, sig87) = gen!(fips204::ml_dsa_87, [5u8; 32], [6u8; 32]);

    let msg_str = String::from_utf8(MSG.to_vec()).unwrap();

    let mut out = String::new();
    writeln!(
        out,
        "// AUTOGENERATED by `cargo run -p jclaw-credential --example gen_mldsa_vectors`.\n\
         // Deterministic ML-DSA (FIPS 204) vectors over a fixed message; consumed by the\n\
         // mldsa_vectors test module and deploy/benchmark-mldsa-devnet.cjs. Do not edit by hand.\n\
         #![allow(dead_code)]\n\n\
         pub const MLDSA_MSG: &[u8] = b\"{msg_str}\";\n"
    )
    .unwrap();

    for (name, pk, sig) in [
        ("MLDSA44", &pk44, &sig44),
        ("MLDSA65", &pk65, &sig65),
        ("MLDSA87", &pk87, &sig87),
    ] {
        writeln!(out, "pub const {name}_PK_HEX: &str = \"{pk}\";").unwrap();
        writeln!(out, "pub const {name}_SIG_HEX: &str = \"{sig}\";\n").unwrap();
    }

    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("mldsa_vectors.rs");
    fs::write(&path, out).unwrap();
    eprintln!("wrote {}", path.display());
    eprintln!(
        "  ML-DSA-44 pk={}B sig={}B | 65 pk={}B sig={}B | 87 pk={}B sig={}B",
        pk44.len() / 2,
        sig44.len() / 2,
        pk65.len() / 2,
        sig65.len() / 2,
        pk87.len() / 2,
        sig87.len() / 2,
    );
}
