# finalize-v3-series.ps1
#
# Produces the complete v3.0.x/ patch series:
#   - Copies the 7 CLEAN v2.2.7 patches verbatim into v3.0.x/.
#   - Assumes 01 has already been regenerated by regen-patch-01-v3.ps1.
#   - Regenerates 04 and 08 via `git apply --3way` then `git diff` against
#     a clean v3.0.1 checkout.
#
# Final step: re-runs check-baseline-v3.ps1 with PATCH_DIR pointed at v3.0.x/
# to confirm the new series applies 10/10 CLEAN.

param(
    [string]$CosmwasmTag = "v3.0.1",
    [string]$BuildDir    = (Join-Path $env:USERPROFILE "junoclaw-build")
)

$ErrorActionPreference = "Continue"

$JunoclawRoot = (Get-Item $PSScriptRoot).Parent.Parent.FullName
$CosmwasmDir  = Join-Path $BuildDir "cosmwasm-bn254"
$SrcDir       = Join-Path $JunoclawRoot "wasmvm-fork\patches\v2.2.7"
$DstDir       = Join-Path $JunoclawRoot "wasmvm-fork\patches\v3.0.x"

if (-not (Test-Path (Join-Path $CosmwasmDir ".git"))) {
    Write-Error "cosmwasm checkout missing; run check-baseline-v3.ps1 first"
    exit 1
}

New-Item -ItemType Directory -Force -Path $DstDir | Out-Null

# --- 1. Copy verbatim CLEAN patches ---------------------------------------
$cleanPatches = @(
    '00-rust-toolchain.toml.patch',
    '02-cosmwasm-std.traits.rs.patch',
    '03-cosmwasm-std.testing.mock.rs.patch',
    '05-cosmwasm-vm.imports.rs.patch',
    '06-cosmwasm-vm.instance.rs.patch',
    '07-cosmwasm-vm.compatibility.rs.patch',
    '09-cosmwasm-crypto-bn254-new-crate.patch'
)

Write-Host "=== Copying CLEAN patches verbatim ==="
foreach ($p in $cleanPatches) {
    Copy-Item (Join-Path $SrcDir $p) (Join-Path $DstDir $p) -Force
    Write-Host "  copied $p"
}

# --- 2. Verify 01 already exists (regenerated by regen-patch-01-v3.ps1) ---
$patch01 = Join-Path $DstDir "01-cosmwasm-std.imports.rs.patch"
if (-not (Test-Path $patch01)) {
    Write-Error "01-cosmwasm-std.imports.rs.patch missing; run regen-patch-01-v3.ps1 first"
    exit 2
}
Write-Host "  ok: 01-cosmwasm-std.imports.rs.patch already present (regenerated separately)"

# --- 3. Regenerate 04 and 08 via --3way + git diff -----------------------
function Invoke-3wayPatchRegen {
    param([string]$PatchName, [string]$RelTargetFile)

    $srcPatch = Join-Path $SrcDir $PatchName
    $dstPatch = Join-Path $DstDir $PatchName

    Write-Host "=== Regenerating $PatchName via --3way ==="

    Push-Location $CosmwasmDir
    try {
        $null = & git reset --hard $CosmwasmTag 2>&1
        $null = & git clean -fdx 2>&1

        $null = & git apply --3way $srcPatch 2>&1
        $rc3way = $LASTEXITCODE
        if ($rc3way -ne 0) {
            Write-Error "  --3way apply failed for $PatchName (rc=$rc3way)"
            return $false
        }

        $diffOut = & git diff -- $RelTargetFile
        if (-not $diffOut) {
            Write-Error "  git diff produced empty output for $PatchName"
            return $false
        }
        [System.IO.File]::WriteAllText($dstPatch, ($diffOut -join "`n") + "`n", (New-Object System.Text.UTF8Encoding($false)))
        Write-Host "  wrote $dstPatch"

        $null = & git checkout -- $RelTargetFile 2>&1
        Write-Host "  reset $RelTargetFile to clean v3.0.1"

        $null = & git apply --check $dstPatch 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Host "  VERIFY OK -- $PatchName applies cleanly" -ForegroundColor Green
            return $true
        } else {
            Write-Error "  VERIFY FAILED -- $PatchName does not apply cleanly"
            return $false
        }
    } finally { Pop-Location }
}

$ok04 = Invoke-3wayPatchRegen -PatchName '04-cosmwasm-std.Cargo.toml.patch' -RelTargetFile 'packages/std/Cargo.toml'
$ok08 = Invoke-3wayPatchRegen -PatchName '08-cosmwasm-vm.Cargo.toml.patch'  -RelTargetFile 'packages/vm/Cargo.toml'

if (-not $ok04 -or -not $ok08) {
    Write-Error "One or more --3way regenerations failed"
    exit 3
}

# --- 4. Final clean reset --------------------------------------------------
Push-Location $CosmwasmDir
try {
    $null = & git reset --hard $CosmwasmTag 2>&1
    $null = & git clean -fdx 2>&1
} finally { Pop-Location }

# --- 5. Re-run baseline check pointing at v3.0.x/ -------------------------
Write-Host ""
Write-Host "=== Re-running baseline check against v3.0.x/ ==="
& powershell -ExecutionPolicy Bypass -File (Join-Path $PSScriptRoot "check-baseline-v3.ps1") -PatchDir $DstDir
exit $LASTEXITCODE
