/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export enum JsGateVerdict {
  Green = 'Green',
  Yellow = 'Yellow',
  Red = 'Red'
}

export interface JsAgentMessage {
  from: Uint8Array
  to: Uint8Array
  content: Uint8Array
  contentHash: Uint8Array
  timestamp: bigint
  jLensGate?: JsGateVerdict
  proposalRef?: bigint
}

export interface JsBatch {
  messages: JsAgentMessage[]
  prevHash: Uint8Array
  height: bigint
  timestamp: bigint
}

export interface JsGateResult {
  verdict: JsGateVerdict
  attestationHash?: string
  separationScore: number
  modelId?: string
}

export function createAgentMessage(
  from: Uint8Array,
  to: Uint8Array,
  content: Uint8Array,
  timestamp: bigint
): JsAgentMessage

export function encodeAgentMessage(msg: JsAgentMessage): Uint8Array

export function decodeAgentMessage(data: Uint8Array): JsAgentMessage

export function verifyMessageHash(msg: JsAgentMessage): boolean

export function isBroadcastMessage(msg: JsAgentMessage): boolean

export function createBatch(
  messages: JsAgentMessage[],
  prevHash: Uint8Array,
  height: bigint,
  timestamp: bigint
): JsBatch

export function hashBatch(batch: JsBatch): Uint8Array

export function batchHasBlockedMessage(batch: JsBatch): boolean

export function batchLen(batch: JsBatch): bigint

export function createGateResult(
  verdict: JsGateVerdict,
  separationScore: number,
  attestationHash?: string,
  modelId?: string
): JsGateResult
