#!/usr/bin/env python3
"""Build a test PublishAnon message for the DAO's moultbook-v0 contract.

This script uses the deterministic test fixture generated by
`circuits/moultbook-membership/src/bin/gen-proof.rs`. The same VK was stored
in the zk-verifier by A12, so the proof should verify on mainnet.

Usage:
    cd ~/junoclaw
    python3 tools/test-publish-anon.py [--topic TOPIC] [--cid CID] [--key-name KEY]

Then copy-paste the printed junod command, or run it if --key-name is provided.
"""

import argparse
import hashlib
import json
import subprocess
from pathlib import Path

# DAO-owned Moultbook infrastructure (from A9)
ZK_VERIFIER = "juno1f7m3p82flvve46nawd6ng5qw7fky3d0ym5pvm4340pwvn7v7g7uqk55v0q"
MOULTBOOK_V0 = "juno18xn4cfpjfpqhmjenr9gdxk5uk7jjq3cezcy6d2jcar2gvx98pvtsm95z6j"
RPC = "https://juno-rpc.publicnode.com:443"
CHAIN_ID = "juno-1"

# Location of the proof artifacts generated by gen-proof
ARTIFACTS_DIR = Path(__file__).parent.parent / "circuits" / "moultbook-membership" / "devnet" / "proof-artifacts"


def sha256_hex(data: str) -> str:
    return hashlib.sha256(data.encode("utf-8")).hexdigest()


def load_b64(filename: str) -> str:
    path = ARTIFACTS_DIR / filename
    with open(path, "r") as f:
        return f.read().strip()


def build_message(topic: str, content_cid: str) -> dict:
    proof_base64 = load_b64("proof.b64")
    public_inputs_base64 = load_b64("inputs.b64")
    topic_hash = sha256_hex(topic)

    return {
        "publish_anon": {
            "topic_hash": topic_hash,
            "content_cid": content_cid,
            "proof_base64": proof_base64,
            "public_inputs_base64": public_inputs_base64,
        }
    }


def build_direct_verify_message() -> dict:
    return {
        "verify_proof": {
            "proof_base64": load_b64("proof.b64"),
            "public_inputs_base64": load_b64("inputs.b64"),
        }
    }


def main():
    parser = argparse.ArgumentParser(description="Build a test PublishAnon tx")
    parser.add_argument(
        "--direct",
        action="store_true",
        help="Send verify_proof directly to the zk-verifier instead of the full PublishAnon flow",
    )
    parser.add_argument(
        "--topic",
        default="heartbeat",
        help="Topic namespace (default: heartbeat)",
    )
    parser.add_argument(
        "--cid",
        default="QmTestPublishAnonA12",
        help="Content CID (default: QmTestPublishAnonA12)",
    )
    parser.add_argument(
        "--key-name",
        default="",
        help="junod key name to sign with. If empty, the command is printed but not run.",
    )
    parser.add_argument(
        "--out",
        default="/tmp/publish_anon_msg.json",
        help="Where to write the message JSON",
    )
    args = parser.parse_args()

    if args.direct:
        msg = build_direct_verify_message()
        target = ZK_VERIFIER
        label = "Direct zk-verifier test"
        with open(args.out, "w") as f:
            json.dump(msg, f, indent=2)
        print(f"Direct verify message written to {args.out}")
    else:
        msg = build_message(args.topic, args.cid)
        target = MOULTBOOK_V0
        label = "PublishAnon test"
        with open(args.out, "w") as f:
            json.dump(msg, f, indent=2)
        print(f"{label} message written to {args.out}")
        print(f"Topic: {args.topic}")
        print(f"Topic hash (SHA-256): {msg['publish_anon']['topic_hash']}")
        print(f"Content CID: {args.cid}")
    print()

    cmd = [
        "junod", "tx", "wasm", "execute", target,
        json.dumps(msg, separators=(",", ":")),
        "--node", RPC,
        "--chain-id", CHAIN_ID,
        "--gas", "auto",
        "--gas-adjustment", "1.5",
        "--gas-prices", "0.075ujuno",
        "--from", args.key_name or "<YOUR_KEY_NAME>",
        "--yes",
    ]

    if args.key_name:
        print(f"Running {label}:")
        print(" ".join(cmd))
        subprocess.run(cmd, check=True)
    else:
        print(f"Copy-paste the following command to run the {label} after replacing <YOUR_KEY_NAME>:")
        print(" ".join(cmd))


if __name__ == "__main__":
    main()
